### ISSUE TITLE
Problem with python execution 

### ISSUE THREAD

**Issue by Ericendre** [Dante383/GKFlasher#27]
Hello, 
I've tinkered with the canbus of our cars a fair bit. by miself.
I was really interested to try your code but I have no background in Python ( Only C# ) 

I've followed your instruction on woth my Linux and Windows PC , getting the same error on both. 

While reading anything, even the ECU ID ( My serial to OBD cable is showing ) , I'm getting this error in the console

```
File "/usr/local/lib/python3.9/dist-packages/gkbus/interface/Interface.py", line 58, in InterfaceABC
    def set_timeout (self, timeout: int | None = None):
TypeError: unsupported operand type(s) for |: 'type' and 'NoneType'
```
I understand you're time is valuable, but if it's a common error can you try pointing me in the right direction ? 

Thanks

**Comment by Dante383** [comment]
And by the way, regarding CANbus: you might want to check out the documentation I prepared: https://opengk.org/index.php?title=SIMK43_CAN_Bus 
Everything that was there to dissect was dissected (except CCP but that's WIP). I also prepared a dbc file for convenience

**Comment by Ericendre** [comment]
> Hi! Awesome to find out that someone outside of OpenGK stumbled upon GKFlasher. For starters:
> 
> 1. are you using the GUI or CLI?
> 2. If CLI, please show me what parameters are you calling it with
> 3. Please show me the rest of the error so I can hopefully identify the cause

I'm so amazed you repsponded that quick ! Thanks 💯 
Tried Both, the 2 are Throwing an error, focusing on the CLI and Linux ( Kali if that mater ) 
I will reply with the error

**Comment by Ericendre** [comment]
> And by the way, regarding CANbus: you might want to check out the documentation I prepared: https://opengk.org/index.php?title=SIMK43_CAN_Bus Everything that was there to dissect was dissected (except CCP but that's WIP). I also prepared a dbc file for convenience

I come from this website, and with info found on openGK I'm ( trying ) to reverse the threads that the official Hyundai Diagnostic tool is sending to the ECU

**Comment by Ericendre** [comment]
```
┌──(root💀Kalilinux)-[/home/ericendre/Desktop/Hyundai Coupe/GKFlasher]
└─# python3 [gkflasher.py](http://gkflasher.py/) -p kline -i ftdi://ftdi:232:A6839FVH/1 --read
[] Selected protocol: kline. Initializing..
Traceback (most recent call last):
File "/home/ericendre/Desktop/Hyundai Coupe/GKFlasher/gkflasher.py", line 299, in <module>
bus = initialize_bus(GKFlasher_config['protocol'], GKFlasher_config[GKFlasher_config['protocol']])
File "/home/ericendre/Desktop/Hyundai Coupe/GKFlasher/gkflasher.py", line 153, in initialize_bus
return gkbus.Bus(protocol, interface=interface, *protocol_config)
File "/usr/local/lib/python3.9/dist-packages/gkbus/__init__.py", line 14, in Bus
module = importlib.import_module(module_name)
File "/usr/lib/python3.9/importlib/__init__.py", line 127, in import_module
return _bootstrap._gcd_import(name[level:], package, level)
File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
File "<frozen importlib._bootstrap>", line 972, in _find_and_load_unlocked
File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
File "<frozen importlib._bootstrap_external>", line 790, in exec_module
File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
File "/usr/local/lib/python3.9/dist-packages/gkbus/interface/__init__.py", line 1, in <module>
from .CanInterface import CanInterface
File "/usr/local/lib/python3.9/dist-packages/gkbus/interface/CanInterface.py", line 7, in <module>
from .Interface import InterfaceABC
File "/usr/local/lib/python3.9/dist-packages/gkbus/interface/Interface.py", line 6, in <module>
class InterfaceABC(metaclass=ABCMeta):
File "/usr/local/lib/python3.9/dist-packages/gkbus/interface/Interface.py", line 58, in InterfaceABC
def set_timeout (self, timeout: int | None = None):
TypeError: unsupported operand type(s) for |: 'type' and 'NoneType'
```

**Comment by Dante383** [comment]
Yep looks like a Python update broke my careless typehinting. I fixed that in the gkbus update I talked about earlier - install version 0.1.93 and it should be good to go


> I come from this website, and with info found on openGK I'm ( trying ) to reverse the threads that the official Hyundai Diagnostic tool is sending to the ECU

If you shared some details about what exactly you're trying to do - chance is, we've already done it but it's not documented yet :) Unless you just like the challenge, of course

**Comment by Ericendre** [comment]
I've tryed with the new version , throwing me the same error

**Comment by Dante383** [comment]
Ups, my fault! Sorry, version 0.1.794 actually

**Comment by Ericendre** [comment]
Wait wait wait, different lines , If I new python I would do that myself but I've never tryed Py 

The new error : 
```
FFile "/usr/local/lib/python3.9/dist-packages/gkbus/interface/__init__.py", line 1, in <module>
from .CanInterface import CanInterface
File "/usr/local/lib/python3.9/dist-packages/gkbus/interface/CanInterface.py", line 10, in <module>
class CanInterface(InterfaceABC):
File "/usr/local/lib/python3.9/dist-packages/gkbus/interface/CanInterface.py", line 28, in CanInterface
def set_timeout (self, timeout: int | None = None):
TypeError: unsupported operand type(s) for |: 'type' and 'NoneType'
```

**Comment by Dante383** [comment]
Now this shouldn't be possible because that line is no longer there. Are you confident you've installed gkbus 0.1.794? If so, instead of debugging PyPi errors for a quick solution you could just go to /usr/local/lib/python3.9/dist-packages/gkbus/interface/CanInterface.py
find the set_timeout declaration in line 28 and replace it with:
def set_timeout (self, timeout: int = None):

**Comment by Ericendre** [comment]
I'm using an microcontroler with embeded CAN module to try to do 2 things : 
- Display oil temp and any other relevant info , I'm monitoring fuel trim and a few other specials things and having a phone with 20 gauges is a little distracting ( also ability to control the IAC via microcontroler , insted of the stock idle map )
- Add sensors to the existing can bus and use thin info to control a few checky breky modules in the engine bay witout redoing the entire wiring

**Comment by Ericendre** [comment]
Okay, instaled 0.1.793 insted of 0.1.794, I have a dependency related error but I think got it, will report soon ! Thanks a lot

**Comment by Dante383** [comment]
You might want to try running the pip command again. Sometimes it displays that desired version cannot be found right after publishing it and it has to be run again

**Comment by Dante383** [comment]
@Ericendre  Awesome! Yeah we do, come on in: https://discord.gg/a4fWuBTfxV
